- python/xorbits/core/data.py
- python/xorbits/core/tests/test_instance_check.py
- python/xorbits/core/utils/docstring.py
- python/xorbits/core/utils/tests/test_docstring.py
- python/xorbits/numpy/core.py
- python/xorbits/numpy/lib/index_tricks.py
- python/xorbits/numpy/mars_adapters/flatiter.py
- python/xorbits/numpy/mars_adapters/tests/test_mars_adapters.py
- python/xorbits/pandas/core.py
- python/xorbits/pandas/groupby.py
- python/xorbits/pandas/mars_adapters/tests/test_pandas_examples.py
- python/xorbits/remote/mars_adapters/tests/test_mars_adapters.py
Implements `__instancecheck__` for `DataRefMeta` to make it works with `isinstance`.
Resolves #61
> enh: Implements `__instancecheck__` for `DataRefMeta`

- python/xorbits/pandas/pandas_adapters/core.py
- python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
Make `DataFrame.to_numpy` an alias of `DataFrame.to_tensor`, so that `DataFrame.to_numpy` will not fall back to pandas.
> ENH: make to_numpy an alias of to_tensor

- python/xorbits/core/utils/docstring.py
- python/xorbits/core/utils/tests/test_docstring.py
- python/xorbits/pandas/pandas_adapters/core.py
Fixes #69
Add warning message like this:
> DOC: Add warnings for methods falling back to pandas

- benchmarks/tpch/run_queries.py
Set `use_arrow_dtype`'s default to False in TPCH benchmark.
Fixes #xxxx
> BUG: Set `use_arrow_dtype`'s default to False in TPCH benchmark

- python/xorbits/core/data.py
- python/xorbits/tests/mock_pydevd_xml.py
- python/xorbits/tests/test_utils.py
- python/xorbits/utils.py
> ENH: Stop executing DataRef when pycharm etc tries to evaluate properties in debug

- python/xorbits/deploy/kubernetes/client.py
- python/xorbits/deploy/kubernetes/config.py
Set `MARS_USE_CGROUP_STAT` environment when creating k8s cluster.
Fixes #139
> BUG: Set `MARS_USE_CGROUP_STAT` environment when creating k8s cluster

- .github/workflows/kubernetes.yaml
Kubernetes is incompatible with Minikube 1.29.0(latest for now).
Here I use fixed 1.23.15 K8s to fix this.
Related issues: https://github.com/kubernetes/minikube/issues/4172
> BUG: Incompatible versions of Minikube and Kubernetes

- doc/source/getting_started/numpy.rst
- Include setup for ```hdf5``` and ```t.hdf5``` in the example for loading an HDF5 file.
- Replace ```rg.random``` with ```np.random.random``` (```rg``` might be ```numpy.random.default_rng``` which xorbits currently doesn't have, and directly using ```numpy.random.default_rng``` seems to create a TypeError due to its tuple return).
- Replace ```pi``` with ```np.pi```
Fixes #151
> DOC: Add note about installing requirements for ```10 minutes to xorbits.numpy```

- python/setup.cfg
- python/xorbits/core/execution.py
- python/xorbits/core/tests/test_execution.py
In interactive env, execute variables in user namespace eagerly to avoid duplicated computation.
Resolves #162
> ENH: execute refs in user ns eagerly

- python/xorbits/_mars/dataframe/datasource/read_csv.py
- python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Support passing `skiprows` when reading from csv files.
Fixes #193
> ENH: Support `read_csv` with passing `skiprows`

- .github/workflows/python.yaml
- python/xorbits/core/data.py
- python/xorbits/core/tests/test_execution.py
- python/xorbits/numpy/mars_adapters/core.py
- python/xorbits/pandas/mars_adapters/core.py
- python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py
For those data with unknown shape, we return 0 when call `len(df)`, which is confused for users. In this PR, trigger execution if its shape is unknown and return the correct length. 
Fixes #216
> BUG: Fix wrong length of DataFrame

- doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deployment_kubernetes.po
- doc/source/user_guide/deployment_kubernetes.rst
- python/xorbits/compat/__init__.py
- python/xorbits/compat/_constants.py
- python/xorbits/deploy/docker/install.sh
- python/xorbits/deploy/kubernetes/_constants.py
- python/xorbits/deploy/kubernetes/client.py
- python/xorbits/deploy/kubernetes/config.py
- python/xorbits/deploy/kubernetes/core.py
- python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
- python/xorbits/deploy/kubernetes/worker.py
- python/xorbits/tests/test_utils.py
- python/xorbits/utils.py
> ENH: Automatically install some version-sensitive packages and  select image for user

- .github/mergify.yml
- .github/workflows/docker-cd.yaml
- .github/workflows/python.yaml
- python/xorbits/_mars/learn/contrib/utils.py
- python/xorbits/_mars/lib/aio/_runners.py
- python/xorbits/_mars/oscar/tests/test_batch.py
- python/xorbits/_mars/tests/test_utils.py
- python/xorbits/_mars/utils.py
- python/xorbits/compat/_constants.py
- python/xorbits/deploy/docker/Dockerfile
- python/xorbits/deploy/docker/Dockerfile.base
- clean code for python 3.7 or below
- drop 3.7
- support 3.11
Fixes #245 
Fixes #246
> BLD: Drop Python 3.7 and support Python 3.11 for docker and CI

- python/xorbits/_mars/tensor/datasource/tests/test_datasource.py
- python/xorbits/_mars/tensor/datasource/tests/test_datasource_execution.py
- python/xorbits/_mars/tensor/datasource/tri.py
Broadcast 1d array of shape ```(x,)``` to ```(x, x)``` (same behavior as numpy). 
Example:
```python
import xorbits.numpy as np
np.tril(np.ones(5))
```
Fixes #280
> BUG: fix error when inputting 1d array for ```np.tril``` 

- python/xorbits/_mars/services/cluster/uploader.py
- python/xorbits/_mars/services/storage/core.py
Stop uploading node info after interpreter shutdown.
Fixes #xxxx
> BUG: Stop uploading node info after interpreter shutdown

- .gitignore
- python/xorbits/_mars/services/cluster/api/oscar.py
- python/xorbits/_mars/services/cluster/api/web.py
- python/xorbits/_mars/services/cluster/backends/base.py
- python/xorbits/_mars/services/cluster/supervisor/node_allocator.py
- python/xorbits/_mars/services/cluster/tests/test_api.py
- python/xorbits/deploy/kubernetes/config.py
- python/xorbits/deploy/kubernetes/core.py
- python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
Fixes #285 
Usage Example :
```python
from xorbits._mars.services.cluster import WebClusterAPI
cluster_api = WebClusterAPI(address='<your k8s cluster endpoint>')
await cluster_api.request_workers(worker_num=1)
```
> ENH: Support Scale Up on K8S

- python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
- python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
- python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
- python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
- python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
- python/xorbits/_mars/dataframe/tests/test_initializer.py
- python/xorbits/_mars/dataframe/tseries/tests/test_tseries_execution.py
- python/xorbits/_mars/deploy/oscar/session.py
- python/xorbits/_mars/deploy/oscar/tests/session.py
- python/xorbits/_mars/services/storage/api/web.py
- python/xorbits/_mars/services/task/execution/mars/fetcher.py
- python/xorbits/_mars/tensor/arithmetic/tests/test_arithmetic_execution.py
- python/xorbits/_mars/tensor/base/tests/test_base_execution.py
In a local deployment, the oscar APIs are generally used by the `Fetcher`. Thus we need to specify `to_cpu=True` when calling the storage API to convert vram object into main memory objects.
This PR make `to_cpu=True` the default behavior of `fetch` to avoid possible gpu related errors on the client side.
This PR also reserves the ability to skip the conversion, mostly for testing.
Resolves #351
> BUG: fetch vram data from local cluster

- python/xorbits/_mars/dataframe/tests/test_utils.py
- python/xorbits/_mars/dataframe/utils.py
- python/xorbits/_mars/storage/cuda.py
- python/xorbits/_mars/storage/tests/test_libs.py
1. Raise `NotImplementedError` when getting object from cuda storage backend with conditions and let the storage handler apply the conditions. See: https://github.com/xprobe-inc/xorbits/blob/1cc4e0ce8ef6699da5f3abee08e09718f091bfdf/python/xorbits/_mars/services/storage/handler.py#L112
2. always use pandas to concat fetched dataframes for repr.
Resolves #382
> BUG: fetching from GPU

- .github/workflows/python.yaml
- python/xorbits/_mars/tests/core.py
- python/xorbits/conftest.py
Setup a testing mechanism for letting current test cases run on GPU. For test cases that can run both on CPU and GPU,
1. always use the `setup_gpu` fixture since `setup_gpu` still works even there's no cuda device available.
2. mark test case with annotation `@support_cuda` so that it will be picked up when running pytest -m cuda, a.k.a. our GPU test suite.
3. in the test case, use the bool fixture `gpu` to init dataframes, series, and tensors. `gpu` is, by default, set to `False` so that test cases in CPU test suites still run on CPU. Our GPU test suite, however, runs with `pytest -m cuda --gpu`, where `gpu` is set to `True`, making the test cases run on GPU.
#369
> TST: reuse existing tests for GPU testing

- python/xorbits/_mars/dataframe/datasource/dataframe.py
- python/xorbits/_mars/dataframe/datasource/from_tensor.py
- python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
1. Support creating a cudf dataframe from a tensor or dict of tensors.
2. Support creating a cudf dataframe from a pandas dataframe.
#361
> BUG: GPU `DataFrame` init from tensors or pandas dataframes

- python/xorbits/_mars/dataframe/datasource/read_parquet.py
- python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
We call `op.estimate_size` to predict memory usage of execution, for `read_parquet`, the estimated size is incorrect in many cases. This PR fixes these and add ut to cover them.
Fixes #375
> BUG: Fix `estimate_size` of `DataFrameReadParquet`

- python/xorbits/_mars/dataframe/datasource/from_tensor.py
- python/xorbits/_mars/dataframe/datasource/series.py
- python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
- python/xorbits/_mars/dataframe/indexing/loc.py
- python/xorbits/_mars/dataframe/indexing/set_axis.py
- python/xorbits/_mars/services/storage/handler.py
1. Allow GPU series init from xorbits, numpy or python list.
2. Fix the following error when fetching a GPU series:
```python
ArrowInvalid: could not convert slice(none, none, none) with type slice: did not recognize python value type when inferring an arrow data type
```
The root cause is that cuDF `iloc` cannot handle a tuple with a single element. Here's the way to reproduce the error:
```python
s = cudf.Series(list(range(100)))
s.iloc[(slice(0, 5),)]
```
Fixes #xxxx
> BUG: series initializer on GPU

- .github/workflows/python.yaml
Pyarrow 12.0.0 released, CI failed due to some compatible issues, fix version for now.
Fixes #xxxx
> CHORE: Fix pyarrow version

- python/xorbits/_mars/dataframe/groupby/aggregation.py
See details in issue #424 .
In this PR, just delete some codes. I have no idea why result should be turned to frame here.
In pandas, agg('size') can return a series.
Fixes #424
> BUG: Fix agg('size') execute map result, which should be a series rather than a df

- .github/mergify.yml
- .github/workflows/python.yaml
- python/xorbits/_mars/deploy/oscar/tests/test_local.py
- python/xorbits/_mars/services/storage/api/oscar.py
- python/xorbits/_mars/services/storage/tests/test_api.py
- python/xorbits/_mars/services/storage/tests/test_service.py
- python/xorbits/_mars/services/storage/tests/test_spill.py
- python/xorbits/_mars/services/storage/tests/test_transfer.py
- python/xorbits/_mars/storage/plasma.py
Compatible with Arrow 12.0.0, mainly for deprecated plasma.
Fixes #xxxx
> CHORE: Compatible with Arrow 12.0.0

- python/xorbits/_mars/dataframe/groupby/aggregation.py
- python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
- python/xorbits/_mars/dataframe/reduction/aggregation.py
- python/xorbits/_mars/dataframe/reduction/core.py
- python/xorbits/_mars/dataframe/reduction/tests/test_reduction.py
- python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
Take function names into consideration when compiling the aggregation functions so that identical functions with different names won't have same input and output keys.
Fixes #432
> BUG: groupby same agg funcs leads to wrong results

- python/xorbits/deploy/docker/Dockerfile.base
For python 3.8 and 3.9 in docker, numpy version should be <1.23.0.
Ref successful CD: https://github.com/xprobe-inc/xorbits/actions/runs/5006470463
failed CD: https://github.com/xprobe-inc/xorbits/actions/runs/4983660373
Seems that conda result not stable when resolving these packages.
> BLD: Restrict numpy version in docker for python 3.8 and 3.9

- doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_documentation.po
Remove `fuzzy` statements so that the translated text could be displayed correctly.
> DOC: remove `fuzzy` statements

- python/xorbits/_mars/dataframe/sort/sort_index.py
- python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
As shown in issue #391. Given a two-level multi-indexed dataframe, `sort_index` should firstly sort the dataframe by level 0. But in xorbits, the dataframe is firstly sorted by level 1.
```
import xorbits.pandas as pd
import xorbits.numpy as np
df = pd.DataFrame({"foo": np.random.randint(10, size=100), "bar": range(100)})
gb_rolling_mean = df.groupby(by="foo", group_keys=True).apply(lambda x: x.rolling(window=10).mean())
print(gb_rolling_mean.sort_index())
```
In the `get_indexer_indexer` method of `pandas`, different methods are selected to calculate the indexer according to whether the level is `None`.
However, in `xorbits` framework, if level is `None` (the default value is `None` when user doesn't set level), level will be updated to list(`[None]`) in `sort_index`, causing `pandas` …
> BUG: fix sort_index bug when level attribute is None

- doc/source/development/contributing_environment.rst
1.Updated the Xorbits build and installation script. The command `python setup.py build_ext -i` may fail if the `xoscar` library is not installed. Running `python -m pip install -e ".[dev]"` first solves the problem.
2.The command `python setup.py build_web` requires Node version 14 or higher. 
Fixes #492
> DOC: Update Xorbits build and installation process

- doc/source/user_guide/deployment_cluster.rst
It is a guide with an example to override default config by using -f flag in documentation.
Fixes #454
> DOC: Adds guide to use `-f` flag to modify default config.

- python/xorbits/_mars/deploy/oscar/local.py
- python/xorbits/_mars/services/scheduling/worker/quota.py
Set hard limit to None for local deployment so that `QuotaActor` won't check available memory when allocate memory, it will reduce false alarms about insufficient memory.
Fixes #503
> ENH: Make memory allocation more aggressive on local

- python/xorbits/_mars/dataframe/sort/psrs.py
- python/xorbits/_mars/dataframe/sort/sort_index.py
- python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
PR https://github.com/xprobe-inc/xorbits/pull/496 fixes add a unittest of `sort_index` without multi-chunk. This PR adds multi-chunk case in `sort_index` unittest.
However, after add `chunk_size` attribute while constructing DataFrame, the unittest gets an error in `searchsorted` method:
When `sort_index` gets inputs of multi-level indexes, the input of `searchsorted` is MultiIndex.
However, `searchsorted` doesn't support MultiIndex or high-level dimension inputs.
If inputs of `searchsorted` is MultiIndex, use `bisect` method to process it or transform it to single-Index according to `level` attribute.
Fixes #xxxx
> BUG: fix `sort_index` bug of multi-level indexed Dataframe with multi-chunk

- python/xorbits/_mars/dataframe/indexing/sample.py
- python/xorbits/_mars/dataframe/indexing/tests/test_indexing_execution.py
Set frac to None, when infer the size
Fixes #529
> BUG: fix dataframe sample

- python/xorbits/_mars/dataframe/datasource/read_sql.py
Use `url.render_as_string(hide_password=False)` instead of `str(url)` to keep password during serialization.
Fixes #xxxx
> BUG: Fix password lost when calling `pd.read_sql`

- python/xorbits/_mars/services/cluster/uploader.py
- python/xorbits/_mars/services/storage/core.py
For some versions of Python, it raises `RuntimeError: cannot schedule new futures after shutdown`, use "cannot schedule new futures " to match error message.
Fixes #xxxx
> BUG: Match more error  message

- python/pyproject.toml
- python/setup.cfg
- python/xorbits/_mars/services/cluster/uploader.py
This error is raised because the thread pool is shutdown in incorrect order. This PR just suppresses errors.
Similar issue: https://github.com/dask/distributed/issues/6087
Fixes #587 
Fixed minimal version
> BUG: Fix RuntimeError: cannot schedule new futures after shutdown

- python/xorbits/_mars/dataframe/datasource/read_csv.py
- python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
Fix `pd.read_csv` with encoding parameter.
Fixes #613
> BUG: Fix `pd.read_csv` with encoding parameter

- python/xorbits/_mars/dataframe/tests/test_utils.py
- python/xorbits/_mars/dataframe/utils.py
Fix `_generate_value` when building mock dataframe.
Fixes #637
> BUG: Fix `_generate_value` when building mock dataframe

- .github/workflows/python.yaml
- python/xorbits/_mars/learn/cluster/_k_means_init.py
- python/xorbits/_mars/learn/cluster/_kmeans.py
- python/xorbits/_mars/learn/cluster/tests/test_k_means.py
- python/xorbits/_mars/learn/datasets/tests/test_samples_generator.py
- python/xorbits/_mars/learn/decomposition/tests/test_pca.py
- python/xorbits/_mars/learn/decomposition/tests/test_truncated_svd.py
- python/xorbits/_mars/learn/metrics/tests/test_classification.py
- python/xorbits/_mars/learn/metrics/tests/test_ranking.py
- python/xorbits/_mars/learn/metrics/tests/test_regression.py
- python/xorbits/_mars/learn/neighbors/base.py
- python/xorbits/_mars/learn/preprocessing/tests/test_data.py
- python/xorbits/_mars/learn/semi_supervised/tests/test_label_propagation.py
- python/xorbits/_mars/learn/utils/core.py
- python/xorbits/_mars/learn/utils/tests/test_multiclass.py
- python/xorbits/_mars/learn/utils/tests/test_validation.py
- support scikit-learn 1.3.0
- compatible with previous version of scikit-learn, tested on scikit-learn 1.2.2
Fixes #558
> ENH: Compatible with scikit-learn 1.3.0

- python/xorbits/_mars/storage/tests/test_libs.py
Fixes https://github.com/xorbitsai/xorbits/issues/638
https://github.com/xorbitsai/xorbits/issues/661
> TST: Add test_put_get_arrow

- python/xorbits/_mars/dataframe/base/pivot_table.py
- python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
Fix dtypes of `pd.pivot_table`.
Fixes #667
> BUG: Fix dtypes of `pd.pivot_table`

- python/xorbits/_mars/dataframe/datasource/read_csv.py
- python/xorbits/_mars/dataframe/tseries/tests/test_tseries_execution.py
- python/xorbits/_mars/dataframe/tseries/to_datetime.py
Related #583 
See https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html.
This can reduce warnings like this when running tpch :
```
/Users/lichengjie/Projects/workspace/xorbits/python/xorbits/_mars/dataframe/tseries/to_datetime.py:195: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
```
> CHORE: disable infer_datetime_format option to reduce warnings

- python/xorbits/_mars/deploy/oscar/local.py
- python/xorbits/_mars/storage/__init__.py
- python/xorbits/_mars/storage/mmap.py
- python/xorbits/_mars/storage/tests/test_libs.py
- python/xorbits/_mars/tests/test_session.py
- python/xorbits/deploy/__init__.py
- python/xorbits/deploy/tests/test_deploy.py
Use mmap as storage backend.
Now Xorbits can run the complete TPCH SF100 queries on a single  MacOS laptop with 32GB memory.
Future work:
- Use shm as the main storage, and use the mmap as spill storage.
> FEAT: MMAP storage backend

- python/xorbits/_mars/config.py
- python/xorbits/_mars/dataframe/groupby/aggregation.py
- python/xorbits/_mars/dataframe/missing/checkna.py
- python/xorbits/_mars/dataframe/missing/dropna.py
- python/xorbits/_mars/dataframe/missing/fillna.py
- python/xorbits/_mars/dataframe/missing/tests/test_missing.py
- python/xorbits/_mars/dataframe/reduction/aggregation.py
- python/xorbits/_mars/dataframe/reduction/all.py
- python/xorbits/_mars/dataframe/reduction/any.py
- python/xorbits/_mars/dataframe/reduction/core.py
- python/xorbits/_mars/dataframe/reduction/count.py
- python/xorbits/_mars/dataframe/reduction/cummax.py
- python/xorbits/_mars/dataframe/reduction/cummin.py
- python/xorbits/_mars/dataframe/reduction/cumprod.py
- python/xorbits/_mars/dataframe/reduction/cumsum.py
- python/xorbits/_mars/dataframe/reduction/custom_reduction.py
- python/xorbits/_mars/dataframe/reduction/kurtosis.py
- python/xorbits/_mars/dataframe/reduction/max.py
- python/xorbits/_mars/dataframe/reduction/mean.py
- python/xorbits/_mars/dataframe/reduction/min.py
- python/xorbits/_mars/dataframe/reduction/prod.py
- python/xorbits/_mars/dataframe/reduction/sem.py
- python/xorbits/_mars/dataframe/reduction/skew.py
- python/xorbits/_mars/dataframe/reduction/sum.py
- python/xorbits/_mars/dataframe/reduction/var.py
Since pandas 2.1.0, ``mode.use_inf_as_na`` has been deprecated. https://github.com/pandas-dev/pandas/issues/51684
- Deprecate `use_inf_as_na` option
Fixes #xxxx
> CHORE: Deprecate ``use_inf_as_na`` option

- python/xorbits/_mars/dataframe/base/cartesian_chunk.py
- python/xorbits/_mars/dataframe/base/core.py
- python/xorbits/_mars/dataframe/merge/merge.py
This PR added auto merge for cartesian_chunk
Fixes #xxxx
> ENH: added auto merge for cartesian_chunk

- python/xorbits/_mars/dataframe/reduction/aggregation.py
- python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
> BUG: `df.agg` with kwargs

- python/xorbits/_mars/optimization/logical/tileable/column_pruning/input_column_selector.py
- python/xorbits/_mars/optimization/logical/tileable/column_pruning/tests/test_input_column_selector.py
> BUG: Column pruning failed when `groupby` by multi series

- python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
- python/xorbits/_mars/dataframe/base/value_counts.py
- python/xorbits/_mars/dataframe/groupby/fill.py
- python/xorbits/_mars/dataframe/hash_utils.py
- python/xorbits/_mars/dataframe/missing/fillna.py
- python/xorbits/_mars/dataframe/missing/tests/test_missing.py
-  Deprecate `downcast`: see https://github.com/pandas-dev/pandas/issues/40988 and https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.fillna.html
- Deprecated is_categorical_dtype(), use isinstance(obj.dtype, pd.CategoricalDtype) instead ([GH 52527](https://github.com/pandas-dev/pandas/issues/52527))
- Compatible with pandas 2.1.1, mainly for `value_counts`
Fixes #xxxx
> CHORE: Deprecate `downcast` in `fillna`

- python/xorbits/_mars/core/base.py
- python/xorbits/_mars/core/entity/tileables.py
- python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
- python/xorbits/_mars/dataframe/core.py
- python/xorbits/_mars/deploy/oscar/session.py
- python/xorbits/core/adapter.py
- python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
> BUG: fix df deep copy

- .pre-commit-config.yaml
- python/xorbits/_mars/dataframe/datasource/read_parquet.py
- python/xorbits/_mars/learn/linear_model/_base.py
- python/xorbits/_mars/learn/linear_model/tests/test_base.py
- python/xorbits/_mars/learn/metrics/pairwise/pairwise.py
- python/xorbits/_mars/tensor/base/tile.py
- python/xorbits/_mars/tensor/utils.py
- Fix a bug when reading parquet from s3
- Fix some code spell by the way.
Fixes #xxxx
> BUG: read parquet from s3 error: No Such Bucket

- python/xorbits/_mars/dataframe/reduction/sum.py
- python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
Fixes https://github.com/xorbitsai/xorbits/issues/733
> Fix reduction agg with UDF

- python/xorbits/_mars/dataframe/base/cartesian_chunk.py
- python/xorbits/_mars/dataframe/base/core.py
- python/xorbits/_mars/dataframe/merge/merge.py
Fix a performance issue caused by `DataFrameAutoMergeMixin`.
Without this PR, TPCH sf1 will have the following error:
```
AssertionError
51%|███████████████████████████████████████████████████▍                                                 |  50.88/100 [00:01<00:00, 50.65it/s]2023-10-13 16:13:55,293 xorbits._mars.services.task.execution.mars.stage 88633 ERROR    Subtask 1bmsxjlcmLYPTmtAN6LlM4X0 errored
Traceback (most recent call last):
File "/Users/lichengjie/Projects/workspace/xorbits/python/xorbits/_mars/services/subtask/worker/processor.py", line 212, in _execute_operand
return execute(ctx, op)
File "/Users/lichengjie/Projects/workspace/xorbits/python/xorbits/_mars/core/operand/core.py", line 492, in execute
result = executor(results, op)
File …
```
> BUG: `merge` performance issue caused by `DataFrameAutoMergeMixin`

- python/xorbits/_mars/optimization/physical/jax.py
- python/xorbits/_mars/tensor/fuse/jax.py
Modify original PR https://github.com/xorbitsai/xorbits/pull/440, which doesn't make full use of the compilation of `jax`, 
this PR re-implements the core `_evaluate` function, referring to https://jax.readthedocs.io/en/latest/autodidax.html#part-2-jaxprs, this PR add a no-recursive and fully jittable `_eval` function.
> ENH: Modify `JAX` fusion optimization

- python/xorbits/_mars/dataframe/groupby/sort.py
- python/xorbits/_mars/dataframe/sort/sort_index.py
- python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
Xorbits' DataFrame `sort_index` is inconsistent with pandas when `axis=1` and `ignore_index=True`.
pandas does it by sorting the index as usual and replacing index (when axis=0) or columns (when axis=1) with RangeIndex.
[Here](https://github.com/pandas-dev/pandas/blob/8b705675bcb8ae86fb03e388e9969a1772236bf0/pandas/core/generic.py#L5032) is the reference code.
So here we follow pandas  and replace index or columns when `ignore_index=True` is passed.
`python/xorbits/_mars/dataframe/groupby/sort.py`:
```python
out_df = in_df.loc[pivots[p_index - 1] :].drop(
index=pivots[p_index - 1], errors="ignore"
)
```
In the latest version, during the map phase of DataFrameGroupbySortShuffle, if `in_df` does not contain the index from pivots, an empty `out_df` is returned.
> BUG: fix compatibility issue of df.sort_index() and df.groupby(sort=True)

- .github/workflows/python.yaml
- CI/requirements-wheel.txt
- python/setup.cfg
- python/xorbits/_mars/serialization/serializables/field_type.py
xorbits is not fully prepared for numpy 2.0. limit numpy version in CI.
Fixes #781
> CHORE: limit numpy<2.0 as xorbits is not fully prepared for it 

- .github/workflows/build-wheel.yaml
- .github/workflows/docker-cd.yaml
- CI/requirements-wheel.txt
- python/xorbits/deploy/docker/Dockerfile.base
Fix CI of uploading PyPI and dockerhub
> BUG: fix CI of pypi & dockerhub 

- python/xorbits/deploy/docker/Dockerfile.base
The Dockerfile is outdated, and this PR fixes this issue.
- fix the following error:
```Error while loading conda entry point: conda-libmamba-solver (libarchive.so.19: cannot open shared object file: No such file or directory)```
- change installation source to official source:
`/opt/conda/bin/conda install -c conda-forge --solver classic`
Test the docker container with pytest unit tests.
> BLD: Fix Docker CI/CD workflow

- python/xorbits/_mars/_utils.pyx
cudf update its Buffer memory structure. It adds a `BufferOwner` structure.
See https://github.com/rapidsai/cudf/blob/branch-24.08/python/cudf/cudf/core/buffer/buffer.py
This PR make Xorbits compatible with the latest cudf memory structure.
> ENH: support cudf Buffer BufferOwner structure

- .github/workflows/python.yaml
- CI/slurm/Dockerfile
- CI/slurm/docker-compose.yml
- CI/slurm/register_cluster.sh
- CI/slurm/slurm.sh
- CI/slurm/start-slurm.sh
- The previous setup relied on the default `base` environment provided by the conda environment in the image `daskdev/dask-jobqueue:slurm`. 
- However, the intended environment is `dask-jobqueue`. 
- To ensure the correct environment is used, a new custom `slurmbase` image is now manually created, and the `dask-jobqueue` environment is activated within the image.
Fixes #xxxx
> BLD: Fix slurm CI/CD workflow

- python/xorbits/_mars/_utils.pyx
- python/xorbits/_mars/dataframe/merge/tests/test_merge_execution.py
fix cudf comp issue:
* buffer: buffer._owner, size, _offset
* cudf and pandas work differently on merge
> ENH: fix cudf comp issue

- .github/workflows/python.yaml
- python/xorbits/_mars/dataframe/datasource/index.py
- python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
- python/xorbits/_mars/dataframe/merge/concat.py
- python/xorbits/_mars/dataframe/merge/merge.py
- python/xorbits/_mars/dataframe/merge/tests/test_merge_execution.py
* Fix cudf groupby tests as cudf (24.08) does not support them.
* update hadoop CI workflow.
* remove juicefs-ci, as it needs extra self-hosted resources, activate when necessary.
> TST: Fix cudf & hadoop failed tests cases

- .github/workflows/asv.yaml
- .github/workflows/python.yaml
- python/xorbits/_mars/_utils.pyx
- python/xorbits/_mars/dataframe/base/accessor.py
- python/xorbits/_mars/dataframe/base/apply.py
- python/xorbits/_mars/dataframe/base/tests/test_apply_execution.py
- python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
- python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
- python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
- python/xorbits/_mars/dataframe/indexing/index_lib.py
- python/xorbits/_mars/dataframe/indexing/tests/test_indexing_execution.py
- python/xorbits/_mars/dataframe/missing/fillna.py
- python/xorbits/_mars/dataframe/missing/tests/test_missing_execution.py
- fix some warning in _mars/dataframe/indexing
- fix fillna's warning caused by method param
Fixes #xxxx
> ENH: Fix some warning caused by deprecation

- .github/workflows/build-wheel.yaml
Rollback download-artifact and upload-artifact to v3.
v4 has breaking changes, see https://github.com/actions/upload-artifact/issues/478.
> BLD: Fix upload PyPI

- doc/source/reference/index.rst
- doc/source/reference/lightgbm/learning.rst
- doc/source/reference/lightgbm/sklearn.rst
- doc/source/reference/xgboost/core.rst
- doc/source/reference/xgboost/learning_api.rst
- doc/source/reference/xgboost/sklearn.rst
- add a comparison table for the APIs of LightGBM and XGBoost. 
- The table provides a side-by-side reference of commonly used methods for both libraries, including links to their respective documentation pages. 
Fixes #xxxx
> DOC: URLs link to original lightgbm and xgboost docs

- python/xorbits/_mars/deploy/oscar/local.py
Run the code below on device with GPU.
```
def main():
async def fun():
await new_cluster(
n_worker=2,
n_cpu=12,
use_uvloop=False,
)
asyncio.run(fun())
if __name__ == "__main__":
main()
```
Fixes #xxxx
> BUG:  fix xoscar.errors.NoIdleSlot when using new_cluster

- .github/workflows/python.yaml
- python/xorbits/_mars/dataframe/datasource/index.py
- python/xorbits/core/tests/test_execution.py
Without this PR, this example will raise an error:
```
import xorbits.pandas as xpd
data = {"a": [1, 2, 3], "b": [4, 5, 6]}
xdf = xpd.DataFrame(data)
xdf.columns = xpd.Index(["c1", "d1"])
print(xdf)
```
Fixes #xxxx
> BUG: set column name when using `xorbits.pandas.Index`

- .github/workflows/python.yaml
- python/xorbits/_mars/lib/sparse/tests/test_sparse.py
- python/xorbits/_mars/services/scheduling/supervisor/tests/test_assigner.py
- python/xorbits/_mars/services/scheduling/supervisor/tests/test_globalresource.py
- python/xorbits/_mars/services/scheduling/supervisor/tests/test_queue_balance.py
- python/xorbits/_mars/tensor/arithmetic/tests/test_arithmetic_execution.py
- python/xorbits/_mars/tensor/core.py
- python/xorbits/_mars/tensor/indexing/tests/test_indexing_execution.py
- python/xorbits/_mars/tensor/linalg/tests/test_linalg_execution.py
- python/xorbits/_mars/tensor/merge/tests/test_merge_execution.py
- python/xorbits/_mars/tensor/reduction/tests/test_reduction_execution.py
- python/xorbits/_mars/tensor/statistics/histogram.py
- python/xorbits/_mars/tensor/tests/test_utils.py
- python/xorbits/_mars/tensor/utils.py
* Upgrade Python version >= 3.10 in `python.yaml` CI tests
* SciPy's sparse array `.A` is deprecated, use `.toarray()` instead
* remove `xorbits.numpy`'s `fetch_corner_data` when printing large arrays to keep compatible with NumPy 2.1+: when printing large NumPy arrays, only the corner data was printed, with the middle part replaced by an ellipsis (`...`). DO NOT need a dedicated `fetch_corner_data` method, that prints the corner data of the array, anymore.
* Update `xorbits.numpy`'s histogram to 2.1+
> ENH: upgrade CI tests to python>=3.10

- python/xorbits/_mars/dataframe/indexing/tests/test_indexing.py
- python/xorbits/_mars/dataframe/sort/tests/test_sort_execution.py
- python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
- python/xorbits/deploy/slurm/tests/test_slurm.py
- Replace `find_executable` with `shutil.which` to address deprecation.
- Resolve `FutureWarning` by ensuring compatible dtype in Pandas operations.
- Explicitly cast values to match column dtype where necessary.
Fixes #xxxx
> ENH: Update deprecated pandas dtype and distutils

- python/xorbits/_mars/dataframe/groupby/apply.py
- Add include_groups field to GroupByApply class
- Update groupby_apply function signature and documentation
- Modify execute method to handle the new parameter
Fixes #xxxx
> ENH: Add `include_groups` parameter into `groupby.apply`

- .github/workflows/asv.yaml
- .github/workflows/build-wheel.yaml
- .github/workflows/docker-cd.yaml
- .github/workflows/python.yaml
- python/setup.cfg
- python/setup.py
This PR optimizes the GitHub Actions workflow for building wheels by:
1. Using the latest versions of GitHub Actions:
- Updated actions/checkout to v4
- Updated actions/upload-artifact to v4
- Updated actions/download-artifact to v4
- Updated pypa/cibuildwheel to v2.16.5
2. Improving the TestPyPI configuration:
- Added conditional logic to determine the target PyPI repository based on the repository name
- When building from a fork (not xorbitsai/xorbits), packages are uploaded to TestPyPI
- When building from the main repository, packages are uploaded to the official PyPI
These changes make the workflow more maintainable and consistent with [scikit-learn's](https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/wheels.yml) approach.
Fixes #845
> BLD: upload pypi CI pipeline

- .github/workflows/python.yaml
- python/xorbits/_mars/dataframe/core.py
- python/xorbits/_mars/dataframe/plotting/tests/test_plot.py
- python/xorbits/_mars/dataframe/reduction/core.py
- python/xorbits/_mars/dataframe/statistics/quantile.py
- python/xorbits/_mars/lib/groupby_wrapper.py
- python/xorbits/_mars/tensor/statistics/percentile.py
- python/xorbits/_mars/tensor/statistics/quantile.py
- python/xorbits/_mars/tensor/statistics/tests/test_statistics.py
- python/xorbits/_mars/tensor/statistics/tests/test_statistics_execution.py
- python/xorbits/_mars/utils.py
- python/xorbits/core/data.py
- Numpy 2.x needs `__array__` must implement 'dtype' and 'copy' keyword arguments. Reference https://numpy.org/doc/stable/user/basics.interoperability.html#dunder-array-interface
- Parameter `interpolation` has been renamed to `method` in `percentile` and `quantile` above Numpy version 1.22.x
- Parameter `grouper` in `group_by` has been removed because it is deprecated and has been removed in latest version of pandas.
Fixes #xxxx
> ENH: Fix deprecation warnings about `__array__` and `quantile`
