xorbitsai/xorbits

benchmarks/tpch/run_queries.py
python/xorbits/__init__.py
python/xorbits/core/__init__.py
python/xorbits/core/adapter.py
python/xorbits/core/data.py
python/xorbits/core/execution.py
python/xorbits/core/tests/test_execution.py

Enh: manual execution

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/other.md
.github/PULL_REQUEST_TEMPLATE.md

Add templates for GitHub issue and pull request.
Fixes #75

chore: Add templates for GitHub issue and pull request

---

doc/source/conf.py

doc: Add social media links

---

README.md
doc/source/index.rst

DOC: Add roadmaps to README.md

---

python/xorbits/core/adapter.py
python/xorbits/core/data.py
python/xorbits/core/tests/test_instance_check.py
python/xorbits/pandas/mars_adapters/__init__.py
python/xorbits/pandas/mars_adapters/core.py
python/xorbits/pandas/mars_adapters/tests/test_execution.py
python/xorbits/pandas/pandas_adapters/core.py
python/xorbits/pandas/tests/test_accessors.py

Enh: execute when export methods being called

---

README.md
doc/source/reference/index.rst
doc/source/reference/xorbits/index.rst
python/xorbits/deploy/__init__.py

DOC: Add xorbits API

---

python/xorbits/core/adapter.py
python/xorbits/core/data.py
python/xorbits/core/tests/test_adapter.py
python/xorbits/core/tests/test_instance_check.py
python/xorbits/core/utils/docstring.py
python/xorbits/numpy/mars_adapters/tests/test_mars_adapters.py
python/xorbits/pandas/__init__.py
python/xorbits/pandas/groupby.py
python/xorbits/pandas/mars_adapters/core.py

Add some tests to increase coverage.
Fixes #xxxx

ENH: Fix some coverage issues

---

python/xorbits/core/adapter.py
python/xorbits/numpy/mars_adapters/__init__.py
python/xorbits/pandas/mars_adapters/__init__.py
python/xorbits/pandas/mars_adapters/core.py
python/xorbits/pandas/mars_adapters/tests/test_user_defined_functions.py

Implements a xorbits wrapper for dataframe user defined functions, it will specify `skip_infer=True` when inference is failed.
Fixes #60

ENH: Handle inference failure for user defined functions

---

doc/source/getting_started/index.rst
doc/source/getting_started/numpy.rst
doc/source/index.rst

getting started doc for `xorbits.numpy`
Resolves #93

DOC: xorbits.numpy getting started

---

doc/source/getting_started/numpy.rst
doc/source/index.rst

1. adjust the order of top-level topics
2. remove unnecessary subtopic
3. optimize the style of note section

DOC: optimize getting started

---

doc/source/getting_started/index.rst
doc/source/getting_started/pandas.rst

Add pandas getting started.
Resolves #104

DOC: pandas getting started

---

python/xorbits/conftest.py
python/xorbits/core/adapter.py
python/xorbits/pandas/mars_adapters/tests/test_user_defined_functions.py
python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
python/xorbits/tests/core.py
python/xorbits/tests/test_config.yml

Use checked session in test fixtures.
Fixes #xxxx

TST: Use checked session in test fixtures

---

python/xorbits/core/adapter.py
python/xorbits/tests/core.py

Remove import from test module which is not included in build.
Fixes #xxxx

BUG: Remove imports from test module

---

doc/source/_templates/autosummary/accessor_callable.rst
python/xorbits/pandas/plotting.py

BUG: PlotAccessor.__call__ is not implemented

---

.github/workflows/build-wheel.yaml
.github/workflows/python.yaml
CI/requirements-wheel.txt
CI/test_basic_execution.py
python/MANIFEST.in
python/pyproject.toml
python/setup.cfg
python/setup.py
python/xorbits/numpy/mars_adapters/core.py

Add a workflow to build wheel, it will be triggered every day at 4:30 UTC as nightly build, or a new tag is pushed which means publish a new release.
Fixes #62

TST: Add CD for xorbits python package

---

python/xorbits/numpy/__init__.py
python/xorbits/web/tests/test_request_web.py

Suppress Numpy warnings
Fixes #xxxx

ENH: Suppress Numpy warnings

---

python/xorbits/pandas/pandas_adapters/__init__.py
python/xorbits/pandas/pandas_adapters/core.py
python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py

ENH: pandas Series and Index fallbacks

---

doc/source/getting_started/index.rst
doc/source/getting_started/installation.rst

DOC: installation

---

.github/workflows/python.yaml
python/xorbits/core/adapter.py
python/xorbits/core/data.py
python/xorbits/core/tests/test_adapter.py
python/xorbits/core/tests/test_execution.py
python/xorbits/pandas/mars_adapters/__init__.py
python/xorbits/pandas/mars_adapters/core.py
python/xorbits/pandas/mars_adapters/tests/test_execution.py
python/xorbits/web/tests/test_request_web.py

- Make Xorbits Data iterable.
- Skip execution for those who owns data.
Fixes #72

ENH: Make Xorbits Data iterable

---

.gitignore
doc/source/getting_started/installation.rst
python/setup.py

Chore: update submodule

---

README.md
doc/source/deployment/cluster.rst
doc/source/deployment/index.rst
doc/source/deployment/local.rst
doc/source/getting_started/installation.rst
doc/source/index.rst

DOC: add deployment doc

---

python/xorbits/pandas/pandas_adapters/core.py

BUG: Add cls method fallback warning

---

README.md
python/xorbits/conftest.py
python/xorbits/web/tests/test_request_web.py

TST: enhance tests stability

---

python/xorbits/core/utils/docstring.py
python/xorbits/core/utils/tests/test_docstring.py

ENH: version disclaimers

---

.github/mergify.yml

Create mergify configuration.
Fixes #xxxx

ENH: Create mergify configuration

---

.github/mergify.yml

Fix mergify configurations.
Fixes #xxxx

Fix mergify configurations

---

.github/mergify.yml

Switch merge method to squash.
Fixes #xxxx

Switch merge method to squash

---

.github/mergify.yml

Automatically update branch.
Fixes #xxxx

Automatically update branch

---

python/setup.cfg
python/xorbits/core/api.py
python/xorbits/core/tests/test_api.py
python/xorbits/deploy/__init__.py
python/xorbits/deploy/tests/__init__.py
python/xorbits/deploy/tests/test_deploy.py
python/xorbits/supervisor.py
python/xorbits/tests/test_cluster.py
python/xorbits/worker.py

FEAT: support starting via `python -m xorbits.{supervisor, worker}`

---

README.md
doc/source/index.rst

DOC: Added API implemented version and plan

---

README.md
doc/source/index.rst

DOC: refine README and doc index

---

.github/workflows/docker-cd.yaml

Build and push Xorbits docker image every tag release and everyday.

BLD: Xorbits CD for Dockerhub

---

python/xorbits/tests/test_cluster.py

Fix test_cluster hanging on MacOS(reproduced by Python3.9), it is caused by unterminated process.
Fixes #xxxx

TST: Fix test_cluster hanging

---

doc/source/deployment/cluster.rst
python/xorbits/tests/test_cluster.py

DOC: Use one supervisoras example for cluster deployment

---

python/xorbits/deploy/__init__.py
python/xorbits/deploy/tests/test_deploy.py

Make sure only one local cluster exists.
Fixes #xxxx

ENH: Make sure only one local cluster exists

---

.github/workflows/kubernetes.yaml
doc/source/deployment/cloud.rst
doc/source/deployment/kubernetes.rst
python/xorbits/deploy/__init__.py
python/xorbits/deploy/docker/Dockerfile
python/xorbits/deploy/docker/install.sh
python/xorbits/deploy/kubernetes/client.py
python/xorbits/deploy/kubernetes/config.py
python/xorbits/deploy/kubernetes/tests/test_config.py
python/xorbits/deploy/kubernetes/tests/test_kubernetes.py

K8s supports installing pip and conda packages.
Fix #147 .

ENH: K8s deployment supports installing pip and conda packages

---

python/setup.cfg

Fix #159 
- [] tests added / passed (if needed)
- [] Ensure all linting tests pass

ENH: Support aws and azure install options

---

python/xorbits/__init__.py
python/xorbits/web/__init__.py
python/xorbits/web/tests/test_request_web.py
python/xorbits/web/ui/src/Dashboard.js
python/xorbits/web/version_handler.py

Fix version displayed on the Web UI.

BUG: Show xorbits release version and commit id on Web UI

---

README.md
doc/source/conf.py
doc/source/index.rst
doc/source/locale/zh_CN/LC_MESSAGES/index.po

BUG: fix all the slack links

---

README.md
doc/source/conf.py
doc/source/index.rst
doc/source/locale/zh_CN/LC_MESSAGES/index.po

BUG: update slack links

---

README.md
doc/Makefile
doc/make.bat
doc/requirements-doc.txt
doc/source/index.rst
doc/source/norm_zh.py

This PR added `make html_zh_cn`.
Fixes #xxxx

DOC: add `make html_zh_cn`

---

python/xorbits/deploy/kubernetes/client.py
python/xorbits/deploy/kubernetes/config.py
python/xorbits/deploy/kubernetes/tests/test_config.py

BUG: Workers pod may turn to running status before supervisor

---

doc/source/locale/zh_CN/LC_MESSAGES/index.po

DOC: add zh_CN translation for index

---

python/xorbits/core/utils/docstring.py
python/xorbits/pandas/core.py

CHORE: Update black

---

doc/source/locale/zh_CN/LC_MESSAGES/deployment/cluster.po
doc/source/locale/zh_CN/LC_MESSAGES/deployment/index.po
doc/source/locale/zh_CN/LC_MESSAGES/deployment/local.po

Translate part of deployment documentations.
Part of #173

DOC: Translate part of deployment documentations into zh_CN

---

doc/source/locale/zh_CN/LC_MESSAGES/deployment/cluster.po
doc/source/locale/zh_CN/LC_MESSAGES/deployment/local.po

DOC: Fix ref link in deployment section

---

.github/workflows/docker-cd.yaml
.github/workflows/kubernetes.yaml
doc/source/deployment/kubernetes.rst
python/xorbits/deploy/docker/Dockerfile
python/xorbits/deploy/docker/Dockerfile.base
python/xorbits/deploy/kubernetes/client.py
python/xorbits/deploy/kubernetes/config.py
python/xorbits/deploy/kubernetes/tests/test_kubernetes.py
python/xorbits/deploy/kubernetes/worker.py
python/xorbits/pandas/pandas_adapters/core.py

Support python 3.7, 3.8, 3.9 and 3.10 for every docker image release.
Resolves #157

BLD: Docker image supports multi python versions

---

doc/source/getting_started/installation.rst
doc/source/locale/zh_CN/LC_MESSAGES/getting_started/index.po
doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
python/setup.cfg

DOC: zh_CN for Installation

---

doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deferred_execution.po
doc/source/locale/zh_CN/LC_MESSAGES/user_guide/index.po

Doc: User guide

---

doc/source/locale/zh_CN/LC_MESSAGES/deployment/cloud.po
doc/source/locale/zh_CN/LC_MESSAGES/deployment/kubernetes.po

DOC: Translate Kubernetes deployment docs

---

README.md
doc/source/getting_started/installation.rst
doc/source/index.rst
doc/source/locale/zh_CN/LC_MESSAGES/getting_started/deployment.po
doc/source/locale/zh_CN/LC_MESSAGES/getting_started/installation.po
doc/source/locale/zh_CN/LC_MESSAGES/index.po

DOC: fix links for README

---

LICENSE

Update Xorbits license
Part of #198

CHORE: Update license

---

README.md

DOC: Add twitter link to README.md

---

.github/workflows/asv.yaml
asv/asv.conf.json
asv/benchmarks/__init__.py
asv/benchmarks/empty_remotes.py
asv/benchmarks/execution.py
asv/benchmarks/graph_assigner.py
asv/benchmarks/graph_builder.py
asv/benchmarks/import.py
asv/benchmarks/learn/__init__.py
asv/benchmarks/learn/metrics.py
asv/benchmarks/learn/model_selection.py
asv/benchmarks/serialize.py
asv/benchmarks/storage.py
asv/benchmarks/util_tokenize.py
python/xorbits/_mars/tensor/__init__.py

Add asv benchmarks and action workflow.
Part of #198

TST: Add asv benchmarks

---

python/xorbits/_mars/optimization/logical/tileable/__init__.py
python/xorbits/_mars/optimization/logical/tileable/column_pruning/input_column_selector.py
python/xorbits/_mars/optimization/logical/tileable/column_pruning/tests/test_input_column_selector.py

BUG: group dataframe by anonymous series

---

.github/workflows/python.yaml
python/setup.cfg
python/xorbits/_mars/optimization/logical/tileable/column_pruning/self_column_selector.py
python/xorbits/_mars/tensor/special/err_fresnel.py

Add checks for _mars module.
Fixes #xxxx

TST: Add checks for _mars module

---

doc/source/index.rst
doc/source/locale/zh_CN/LC_MESSAGES/index.po

DOC: update benchmark links

---

python/xorbits/_mars/deploy/oscar/local.py

Remove `_is_exiting_future` in "python/xorbits/_mars/deploy/oscar/local.py" which is unclear, let's try deleting it first.
Fixes #222

CLN: Remove `_is_exiting_future`

---

python/xorbits/deploy/kubernetes/client.py
python/xorbits/deploy/kubernetes/config.py

BUG: add sleep when waiting for endpoint ready in K8s

---

python/setup.cfg

Fix url in setup.cfg
Fixes #xxxx

CHORE: Fix url in setup.cfg

---

.pre-commit-config.yaml
python/setup.cfg

Update codespell and append skip words to make CI pass.
Fixes #xxxx

CHORE: Update codespell

---

python/xorbits/deploy/docker/Dockerfile

BUG: delete node_modules dir in docker

---

python/xorbits/deploy/docker/Dockerfile.base

CHORE: Fix openssl version in k8s

---

CI/requirements-wheel.txt
python/pyproject.toml

Fix requirements for building wheel.
Fixes #xxxx

BLD: Fix requirements for building wheel

---

.github/workflows/build-wheel.yaml
.github/workflows/python.yaml
python/pyproject.toml
python/setup.cfg

Add python *cp311* wheel support & drop *cp37* wheel build.
Part of #245 #246

BLD: Add python *cp311* wheel support & drop *cp37* wheel build

---

python/xorbits/_mars/deploy/oscar/cmdline.py
python/xorbits/_mars/deploy/oscar/pool.py
python/xorbits/_mars/deploy/yarn/config.py
python/xorbits/deploy/__init__.py

BUG: default logging not applied in interactive mode

---

python/xorbits/_mars/__init__.py
python/xorbits/_mars/deploy/oscar/local.py
python/xorbits/_mars/deploy/oscar/session.py
python/xorbits/_mars/utils.py

ENH: init extension entry point when importing

---

python/xorbits/_mars/dataframe/window/rolling/aggregation.py
python/xorbits/_mars/dataframe/window/rolling/core.py
python/xorbits/_mars/dataframe/window/rolling/tests/test_rolling_execution.py

Implement `DataFrame.rolling.corr`.
Resolves #300 
Resolves #303

FEAT: impl rolling.corr

---

doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deployment_kubernetes.po
doc/source/user_guide/deployment_kubernetes.rst

DOC: K8s drops support for 3.7 and adds support for 3.11

---

python/xorbits/_mars/dataframe/datasource/read_csv.py
python/xorbits/_mars/dataframe/datasource/read_parquet.py
python/xorbits/_mars/dataframe/datasource/tests/test_datasource.py
python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
python/xorbits/_mars/dataframe/datasource/utils.py
python/xorbits/pandas/pandas_adapters/core.py

Fix runtime error caused by `read_csv` with relative path.
Resolves #271

BUG: runtime error caused by read_csv and read_parquet with relative path

---

.github/workflows/python.yaml
doc/requirements-doc.txt
python/setup.cfg

Pandas has released 2.0, there're some compatibility issues in Xorbits, fix version first to let CI pass.
Fixes #xxxx

TST: Fix pandas version

---

README.md
doc/source/getting_started/deployment.rst
doc/source/getting_started/index.rst
doc/source/index.rst
doc/source/locale/zh_CN/LC_MESSAGES/getting_started/deployment.po
doc/source/locale/zh_CN/LC_MESSAGES/index.po

DOC: added SLURM doc links

---

python/xorbits/_mars/deploy/oscar/local.py
python/xorbits/_mars/deploy/oscar/tests/test_local.py

Fix local init for multiple GPU devices.
Fixes #324

BUG: Fix local init for multiple GPU devices

---

python/xorbits/core/data.py
python/xorbits/core/tests/test_execution.py

BUG: Int Auto Conversion

---

python/xorbits/_mars/dataframe/core.py
python/xorbits/_mars/dataframe/tests/test_core.py

BUG: unexpected error from `DataFrame.__mars_tensor__`

---

benchmarks/tpch/run_queries.py

Add options to TPC-H benchmarking script for GPU env.

ENH: GPU benchmark script

---

python/xorbits/_mars/learn/cluster/_k_means_common.py
python/xorbits/_mars/learn/cluster/_k_means_elkan_iter.py
python/xorbits/_mars/learn/cluster/_k_means_lloyd_iter.py
python/xorbits/_mars/learn/metrics/pairwise/haversine.py
python/xorbits/_mars/learn/metrics/pairwise/pairwise_distances_topk.py
python/xorbits/_mars/learn/preprocessing/normalize.py
python/xorbits/_mars/learn/utils/shuffle.py
python/xorbits/_mars/lib/sparse/__init__.py
python/xorbits/_mars/lib/sparse/array.py
python/xorbits/_mars/lib/sparse/core.py
python/xorbits/_mars/tensor/array_utils.py
python/xorbits/_mars/tensor/base/astype.py
python/xorbits/_mars/tensor/base/psrs.py
python/xorbits/_mars/tensor/base/unique.py
python/xorbits/_mars/tensor/datasource/array.py
python/xorbits/_mars/tensor/einsum/core.py
python/xorbits/_mars/tensor/linalg/cholesky.py
python/xorbits/_mars/tensor/linalg/lu.py
python/xorbits/_mars/tensor/linalg/solve_triangular.py
python/xorbits/_mars/tensor/random/core.py
python/xorbits/_mars/tensor/random/multivariate_normal.py
python/xorbits/_mars/tensor/spatial/distance/cdist.py
python/xorbits/_mars/tensor/spatial/distance/pdist.py
python/xorbits/_mars/tensor/spatial/distance/squareform.py
python/xorbits/_mars/tensor/special/core.py
python/xorbits/_mars/tests/test_utils.py
python/xorbits/_mars/utils.py

BUG: equality assertion on lazy loaded cupy

---

python/xorbits/core/data.py
python/xorbits/core/tests/test_execution.py

Add auto bool and float conversion
Fixes #318 
Fixes #321

BUG: Xorbits.numpy raises TypeError 

---

python/xorbits/_mars/services/storage/api/oscar.py
python/xorbits/_mars/services/storage/api/web.py
python/xorbits/_mars/services/storage/handler.py
python/xorbits/_mars/services/storage/tests/test_service.py

Add an option for `StorageAPI.get` to convert `cudf` data structures to `pandas` data structures.
Resolves #348 
Resolves #327

BUG: fetch vram data from cluster

---

python/xorbits/_mars/core/operand/core.py
python/xorbits/_mars/dataframe/reduction/aggregation.py
python/xorbits/_mars/dataframe/reduction/core.py
python/xorbits/_mars/dataframe/reduction/nunique.py
python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py
python/xorbits/_mars/tests/core.py

- Fix df.agg issues on GPU
- Support series.agg on GPU
Fixes #333 
Fixes #337 
Remain issues #344 #345 #358 to be fixed in other PRs.

ENH: Support DF and Series agg on GPU 

---

python/xorbits/_mars/dataframe/reduction/tests/test_reduction_execution.py

1. modify test case names
2. fix GPU test cases by specifying the fetch parameter `to_cpu=False`
Resolves #371

TST: fix GPU tests

---

python/xorbits/deploy/__init__.py

BUG: destory session in xorbits.shutdown

---

python/xorbits/_mars/dataframe/arithmetic/core.py
python/xorbits/_mars/dataframe/arithmetic/tests/test_arithmetic_execution.py

BUG: DataFrameBinOp tile output dtype is wrong

---

python/xorbits/_mars/services/scheduling/worker/execution.py
python/xorbits/_mars/services/scheduling/worker/tests/test_execution.py
python/xorbits/_mars/services/subtask/worker/processor.py

BUG: Fix batch put and fetch data on GPU

---

CI/install-hadoop.sh
python/xorbits/_mars/deploy/oscar/pool.py

Move the logic for handling this `n_io_process` to xorbits.
Fixes #397

ENH: Move the logic for handling this `n_io_process` to xorbits

---

.github/workflows/python.yaml
python/xorbits/_mars/storage/filesystem.py
python/xorbits/_mars/storage/tests/test_libs.py

Add alluxio as an alternative storage

FEAT: add alluxio storage lib

---

python/xorbits/_mars/dataframe/core.py
python/xorbits/_mars/dataframe/datasource/index.py
python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py
python/xorbits/_mars/tests/core.py

BUG: GPU index initializer

---

python/xorbits/_mars/dataframe/merge/merge.py
python/xorbits/_mars/dataframe/merge/tests/test_merge_execution.py
python/xorbits/_mars/dataframe/utils.py
python/xorbits/_mars/services/storage/handler.py
python/xorbits/_mars/services/subtask/worker/processor.py

BUG: Fix merge and join on GPU

---

python/xorbits/_mars/dataframe/indexing/iloc.py
python/xorbits/_mars/dataframe/indexing/tests/test_indexing_execution.py

1. Fix GPU dataframe `iloc` execution.

BUG: gpu dataframe iloc

---

python/xorbits/_mars/dataframe/core.py
python/xorbits/core/adapter.py
python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py

BUG: Wrong dataframe id value

---

doc/source/locale/zh_CN/LC_MESSAGES/development/contributing.po
doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_documentation.po

Translate the git usage part to Chinese.

DOC: git usage zh_cn

---

doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/array-creation.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/array-manipulation.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/bitwise.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/indexing.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/io.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/linalg.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/logic.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/math.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/set.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/sort.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/numpy/statistics.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/frame.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/general_functions.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/groupby.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/indexing.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/io.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/series.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/pandas/window.po
doc/source/locale/zh_CN/LC_MESSAGES/reference/xorbits/index.po

Update the pot files. So that developers working on docs won't be confused.
Fixes #xxxx

DOC: update pot files

---

.github/workflows/python.yaml

Check doc building in lint CI to replace using readthedocs webhook.
Fixes #xxxx

DOC: Check doc building in CI

---

.github/mergify.yml

Modify mergify.yml as workflows changed.
Fixes #xxxx

CHORE: Modify mergify

---

python/xorbits/core/adapter.py
python/xorbits/numpy/__init__.py
python/xorbits/numpy/numpy_adapters/__init__.py
python/xorbits/numpy/numpy_adapters/core.py
python/xorbits/numpy/numpy_adapters/tests/test_numpy_adapters.py
python/xorbits/pandas/pandas_adapters/core.py

ENH: Support numpy.ndarray fallback to numpy

---

python/xorbits/pandas/mars_adapters/tests/test_mars_adapters.py
python/xorbits/pandas/pandas_adapters/core.py

BUG: series.tolist()[0] get Attribute Error

---

doc/source/development/contributing_environment.rst
doc/source/locale/zh_CN/LC_MESSAGES/development/contributing_environment.po

DOC: Fix docker development doc

---

python/xorbits/pandas/pandas_adapters/core.py
python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py

Fix the bug of read_pickle
Resolve #298

BUG: fix read pickle bug and add UT

---

python/xorbits/_mars/dataframe/base/pivot_table.py

- add fine-grained chunk combination choice

ENH: update pivot_table op

---

python/xorbits/_mars/_utils.pyx

- Solve the segmentation fault when the size of np.array is large
Fixes #366

ENH: update tokenizing numpy

---

python/xorbits/_mars/dataframe/base/pivot.py
python/xorbits/_mars/dataframe/base/tests/test_base_execution.py

- support one chunk simplification
- add shape infer and combine op

ENH: update pivot op

---

python/xorbits/_mars/dataframe/merge/tests/test_merge_execution.py
python/xorbits/_mars/optimization/logical/tileable/tests/test_head.py
python/xorbits/_mars/tensor/reduction/core.py
python/xorbits/_mars/tensor/statistics/tests/test_statistics.py
python/xorbits/core/adapter.py
python/xorbits/numpy/__init__.py
python/xorbits/numpy/fft/__init__.py
python/xorbits/numpy/linalg/__init__.py
python/xorbits/numpy/mars_adapters/tests/test_numpy_examples.py
python/xorbits/numpy/numpy_adapters/core.py
python/xorbits/numpy/numpy_adapters/tests/test_numpy_adapters.py
python/xorbits/numpy/random/__init__.py

- fix named tuple adapter
- fix doc
Fixes #xxxx

Bug: Fix numpy CI

---

README.md
doc/source/reference/index.rst
doc/source/reference/xgboost/core.rst
doc/source/reference/xgboost/index.rst
doc/source/reference/xgboost/learning_api.rst
doc/source/reference/xgboost/sklearn.rst
python/xorbits/__init__.py
python/xorbits/xgboost/__init__.py
python/xorbits/xgboost/mars_adapters/core.py

DOC: Init Xgboost Doc

---

doc/source/getting_started/installation.rst

Updated `getting_started/installation.rst` with updated python version (removes all occurrences of python 3.7 as it is no longer used). 
Fixes #500

DOC: Updated doc for python support version

---

doc/source/index.rst
python/setup.cfg

Add xgboost as requirement for doc building.
Fixes #xxxx

DOC: Install xgboost for doc building

---

python/xorbits/lightgbm/__init__.py
python/xorbits/lightgbm/mars_adapters/core.py

BUG: fix lightgbm

---

python/xorbits/_mars/learn/utils/multiclass.py
python/xorbits/core/adapter.py
python/xorbits/lightgbm/mars_adapters/core.py
python/xorbits/xgboost/mars_adapters/core.py

Suppress scipy warnings.
Fixes #xxxx

BUG: Suppress scipy warnings

---

python/xorbits/_mars/lib/sparse/tests/test_sparse.py

BUG: fix sparse divide CI

---

python/xorbits/_mars/learn/contrib/joblib/tests/test_backend.py

BUG: fix joblib CI

---

doc/source/locale/zh_CN/LC_MESSAGES/user_guide/deployment_kubernetes.po
doc/source/user_guide/deployment_kubernetes.rst

DOC: Add Chinese doc for external storage JuiceFS on K8S

---

.github/workflows/python.yaml

TST: Fix version of sklearn

---

python/xorbits/core/adapter.py
python/xorbits/core/tests/test_execution.py

Fixes https://github.com/xorbitsai/xorbits/issues/586

BUG: Fix StringAccessor __getitem__ error

---

python/xorbits/_mars/lib/filesystem/_glob.py
python/xorbits/_mars/lib/filesystem/fsspec_adapter.py

- Fix read parquet on s3. s3.fs.ls will return the directory itself

BUG: Fix Read Parquet

---

.github/workflows/python.yaml

constrain version of lightgbm
None

BUG: Fix LGBM CI

---

python/xorbits/_mars/core/entity/objects.py
python/xorbits/_mars/remote/tests/test_remote_function.py
python/xorbits/_mars/resource.py
python/xorbits/_mars/services/cluster/uploader.py
python/xorbits/_mars/services/storage/core.py
python/xorbits/_mars/utils.py
python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py
python/xorbits/remote/mars_adapters/tests/test_mars_adapters.py

- Fetch to local when print object data
- Fix unexpected logs and suppress warnings
Fixes #597

BUG: Fetch to local when print object data

---

.github/workflows/python.yaml
python/xorbits/_mars/learn/contrib/lightgbm/_train.py
python/xorbits/_mars/learn/contrib/lightgbm/tests/test_classifier.py
python/xorbits/_mars/learn/contrib/lightgbm/tests/test_ranker.py
python/xorbits/_mars/learn/contrib/lightgbm/tests/test_regressor.py
python/xorbits/lightgbm/tests/test_classifier.py
python/xorbits/lightgbm/tests/test_ranker.py
python/xorbits/lightgbm/tests/test_regressor.py

Fix compatibility with the newest lightgbm
Fixes #xxxx

BUG: Fix compatibility with the newest lightgbm

---

python/xorbits/_mars/services/task/analyzer/analyzer.py
python/xorbits/_mars/services/task/analyzer/fusion.py
python/xorbits/_mars/services/task/analyzer/tests/test_fusion.py

Optimize the coloring algorithm to increase task parallelism.
Fixes #384

ENH: Optimize graph fusion

---

python/xorbits/_mars/lib/filesystem/_glob.py
python/xorbits/_mars/lib/filesystem/tests/test_fsspec_adapter.py

BUG: fix s3 glob

---

python/setup.cfg
python/xorbits/_mars/services/scheduling/worker/execution.py
python/xorbits/core/tests/test_execution.py

FEAT: Raise clearer errors when encountering OOM
Fixes https://github.com/xorbitsai/xorbits/issues/562

FEAT: Raise clearer errors when encountering OOM

---

doc/source/getting_started/examples.rst
doc/source/user_guide/best_practices.rst
doc/source/user_guide/index.rst
doc/source/user_guide/loading_data.rst
doc/source/user_guide/read_parquet.rst

Add best practice for loading data.
Fixes #376

DOC: Add best practice for loading data

---

python/xorbits/_mars/dataframe/datasource/from_tensor.py
python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py

BUG: fix from_tensor

---

doc/source/libraries/xorbits_data/datasets.rst
doc/source/libraries/xorbits_data/index.rst
doc/source/reference/datasets/dataset.rst
doc/source/reference/datasets/index.rst
doc/source/reference/datasets/io.rst
doc/source/reference/index.rst
python/setup.cfg
python/xorbits/core/utils/docstring.py
python/xorbits/datasets/__init__.py
python/xorbits/datasets/adapter.py
python/xorbits/datasets/backends/huggingface/core.py
python/xorbits/datasets/dataset.py

Doc: Datasets doc

---

python/xorbits/experimental/dedup.py
python/xorbits/experimental/tests/test_text_dedup.py
python/xorbits/experimental/utils.py

- add exact hash
- refine code structure

ENH: add dedup method

---

python/xorbits/_mars/dataframe/base/_duplicate.py
python/xorbits/_mars/dataframe/base/tests/test_base_execution.py

- fix drop_duplicates no dtypes
- add UT
Fixes #549

BUG: fix drop_duplicates no dtypes

---

.github/workflows/python.yaml

CHORE: add msbuild to CI

---

doc/source/libraries/xorbits_data/datasets.rst
python/xorbits/_mars/core/entity/output_types.py
python/xorbits/_mars/services/meta/metas.py
python/xorbits/_mars/services/task/supervisor/tests/task_preprocessor.py
python/xorbits/_mars/utils.py
python/xorbits/datasets/backends/huggingface/core.py
python/xorbits/datasets/backends/huggingface/getitem.py
python/xorbits/datasets/backends/huggingface/loader.py
python/xorbits/datasets/backends/huggingface/map.py
python/xorbits/datasets/backends/huggingface/rechunk.py
python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
python/xorbits/datasets/backends/huggingface/to_dataframe.py
python/xorbits/datasets/dataset.py

Fixes https://github.com/xorbitsai/xorbits/issues/618

Feat: Basic datasets getitem

---

doc/source/libraries/xorbits_data/datasets.rst
python/xorbits/_mars/learn/contrib/lightgbm/classifier.py
python/xorbits/_mars/learn/contrib/lightgbm/ranker.py
python/xorbits/_mars/learn/contrib/lightgbm/regressor.py
python/xorbits/_mars/learn/contrib/xgboost/classifier.py
python/xorbits/_mars/learn/contrib/xgboost/core.py
python/xorbits/_mars/learn/contrib/xgboost/regressor.py
python/xorbits/_mars/lib/mkl_interface.py
python/xorbits/datasets/backends/huggingface/loader.py
python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py

Fixes https://github.com/xorbitsai/xorbits/issues/632

BUG: Fix Huggingface dataset loader filelock conflict

---

.github/workflows/python.yaml
doc/source/reference/datasets/dataset.rst
python/setup.cfg
python/xorbits/datasets/backends/huggingface/core.py
python/xorbits/datasets/backends/huggingface/export.py
python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
python/xorbits/datasets/dataset.py

FEAT: Export dataset

---

python/xorbits/deploy/docker/Dockerfile.base

BLD: fix docker build on python 3.11

---

python/xorbits/deploy/docker/Dockerfile.base

BLD: add datasets dependency in docker base image 

---

.github/workflows/python.yaml
python/xorbits/datasets/backends/huggingface/export.py
python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
python/xorbits/datasets/iterable_dataset.py
python/xorbits/datasets/tests/test_iterable_dataset.py

Implement an iterable dataset to read export dataset, it contains these features.
Fixes #xxxx

FEAT: Iterable dataset

---

python/xorbits/deploy/kubernetes/client.py
python/xorbits/deploy/kubernetes/external_storage/juicefs/config.py

TST: K8s with juicefs CI may leads to pv conflict

---

python/xorbits/datasets/__init__.py
python/xorbits/datasets/adapter.py
python/xorbits/datasets/backends/__init__.py
python/xorbits/datasets/backends/huggingface/__init__.py
python/xorbits/datasets/backends/huggingface/core.py
python/xorbits/datasets/backends/huggingface/export.py
python/xorbits/datasets/backends/huggingface/from_huggingface.py
python/xorbits/datasets/backends/huggingface/getitem.py
python/xorbits/datasets/backends/huggingface/map.py
python/xorbits/datasets/backends/huggingface/rechunk.py
python/xorbits/datasets/backends/huggingface/tests/__init__.py
python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
python/xorbits/datasets/backends/huggingface/to_dataframe.py
python/xorbits/datasets/dataset.py
python/xorbits/datasets/iterable_dataset.py
python/xorbits/datasets/operand.py
python/xorbits/datasets/tests/test_iterable_dataset.py

Fix copyright

---

python/pyproject.toml

Remove win32 support
Fixes #xxxx

CHORE: Remove win32 support

---

.github/workflows/build-wheel.yaml

BIL: git reset to fix dirty tag

---

.github/mergify.yml

CHORE: Modify required reviews

---

benchmarks/tpch/run_queries.py

https://www.tpc.org/TPC_Documents_Current_Versions/pdf/TPC-H_v3.0.1.pdf
https://github.com/dragansah/tpch-dbgen/tree/master/answers
Fixes #xxxx

BUG: Fix tpch

---

.github/workflows/python.yaml

CHORE: Fix Pandas <= 2.0.3 for now

---

benchmarks/tpch/README.md
benchmarks/tpch/generate_data_pq.py
benchmarks/tpch/loader.py
benchmarks/tpch/run_queries.py

DOC: Readme for tpch benchmark script

---

python/xorbits/_mars/storage/core.py
python/xorbits/_mars/storage/mmap.py

ENH: Use memoryview to open reader in MMAP storage backend

---

.github/workflows/python.yaml
python/xorbits/_mars/dataframe/datasource/read_parquet.py
python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py

FEAT: support loading zip file for read_parquet

---

.github/workflows/python.yaml
doc/source/libraries/xorbits_data/pandas.rst
python/xorbits/_mars/dataframe/arrays.py
python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
python/xorbits/_mars/dataframe/groupby/aggregation.py
python/xorbits/_mars/dataframe/groupby/fill.py
python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py
python/xorbits/_mars/dataframe/hash_utils.py
python/xorbits/_mars/dataframe/reduction/aggregation.py
python/xorbits/_mars/dataframe/tests/test_utils.py
python/xorbits/_mars/dataframe/utils.py
python/xorbits/pandas/mars_adapters/tests/test_pandas_examples.py
python/xorbits/pandas/pandas_adapters/core.py
python/xorbits/pandas/pandas_adapters/tests/test_pandas_adapters.py

ENH: Compatible with Pandas 2.1.0

---

python/setup.cfg

CHORE: fsspec as dependency

---

python/xorbits/_mars/dataframe/core.py
python/xorbits/_mars/dataframe/tests/test_core.py

Implement the array protocol for series and index.
Resolves #528 #527

ENH: impl array protocol for series and index

---

python/xorbits/deploy/docker/Dockerfile.base

See :
- https://github.com/pypa/pip/issues/8314
- https://github.com/Azure/azure-sdk-for-python/issues/32056
Test passed:
https://github.com/ChengjieLi28/xorbits/actions/runs/6187248378/job/16796694300
Fixes #xxxx

BLD: ADLFS import error and docker build failed

---

python/xorbits/_mars/tensor/core.py
python/xorbits/_mars/tensor/tests/test_core_execution.py
python/xorbits/numpy/numpy_adapters/tests/test_numpy_adapters.py

BUG: Tensor map chunk error when func is `tolist`

---

.github/workflows/python.yaml

`import skein` error when the latest `grpcio` is installed
Fixes #xxxx

CHORE: Fix hadoop CI

---

.github/workflows/asv.yaml
python/xorbits/_mars/learn/neighbors/base.py

- See https://github.com/scikit-learn/scikit-learn/pull/26754
Fixes #xxxx

ENH: Compatible with scikit-learn 1.3.1

---

python/xorbits/_mars/dataframe/groupby/__init__.py
python/xorbits/_mars/dataframe/groupby/nth.py
python/xorbits/_mars/dataframe/groupby/tests/test_groupby_execution.py

Add `dataframe.groupby.nth` , a counter part for https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.core.groupby.GroupBy.nth.html
Very much in progress
Fixes  https://github.com/xorbitsai/xorbits/issues/634

FEAT: Add `Dataframe.Groupby.nth`

---

.github/workflows/python.yaml
python/xorbits/_mars/dataframe/groupby/aggregation.py
python/xorbits/_mars/dataframe/groupby/nunique.py
python/xorbits/_mars/dataframe/groupby/tests/test_groupby_nunique_execution.py

BUG: df.groupby.agg error when func is nunique with tuple kwargs

---

python/xorbits/_mars/dataframe/base/tests/test_base_execution.py
python/xorbits/_mars/dataframe/groupby/aggregation.py
python/xorbits/_mars/dataframe/groupby/nunique.py
python/xorbits/_mars/dataframe/groupby/tests/test_groupby_nunique_execution.py

ENH: groupby.nunique supports by series

---

python/xorbits/_mars/dataframe/datasource/read_csv.py
python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py

Fixes https://github.com/xorbitsai/xorbits/issues/735

BUG: Fix read_csv with index_col

---

python/xorbits/_mars/dataframe/datasource/core.py
python/xorbits/_mars/dataframe/datasource/read_csv.py
python/xorbits/_mars/dataframe/datasource/tests/test_datasource_execution.py

FEAT: Support `read_csv` via `http`

---

python/xorbits/_mars/optimization/logical/tileable/column_pruning/column_pruning_rule.py
python/xorbits/_mars/optimization/logical/tileable/column_pruning/tests/test_column_pruning.py

BUG: column pruning causes missing columns on `DataFrameIndex` op

---

python/xorbits/_mars/dataframe/datasource/read_parquet.py

Fix the bug of read s3 parquet

BUG: fix read s3 parquet

---

.github/workflows/build-wheel.yaml
CI/requirements-wheel.txt

BLD: Fix macos and windows build CI

---

.github/workflows/build-wheel.yaml

Test it on my repo: https://github.com/luweizheng/xorbits/actions/runs/9886844806/

BLD: Fix macos build wheel CI

---

.github/workflows/python.yaml

update workflow yaml:
- kubernetes module only use ubuntu-latest/python3.11
- update self-host environment
Fixes #xxxx

BLD: update CI test workflow yaml

---

.github/workflows/build-wheel.yaml
.github/workflows/python.yaml
python/xorbits/web/ui/package-lock.json
python/xorbits/web/ui/package.json

ENH: update web packages version

---

.github/workflows/build-wheel.yaml
.github/workflows/python.yaml
CI/requirements-wheel.txt
CI/test_basic_execution.py
python/pyproject.toml
python/xorbits/_mars/_utils.pyx
python/xorbits/_mars/contrib/dask/tests/test_dask.py
python/xorbits/_mars/storage/tests/test_libs.py
python/xorbits/_mars/tensor/base/moveaxis.py
python/xorbits/_mars/tensor/lib/index_tricks.py
python/xorbits/_mars/utils.py

BLD: Support python 3.12

---

.github/workflows/build-wheel.yaml
.github/workflows/docker-cd.yaml

BLD: build wheel CI upgrade macos-12 to macos-13

---

.github/workflows/python.yaml
python/xorbits/datasets/backends/huggingface/tests/test_huggingface_dataset.py
python/xorbits/pandas/mars_adapters/core.py

- fix issue https://github.com/xorbitsai/xorbits/issues/516
- `lhoestq/test` repository has been deleted now, so it is removed temporarily.
Fixes #xxxx

ENH: remove unreachable constructors wrappers from `xorbits.pandas` & remove `lhoestq/test` huggingface repo in datasets test

---

.github/workflows/python.yaml
python/xorbits/_mars/deploy/oscar/tests/test_local.py
python/xorbits/_mars/lib/nvutils.py
python/xorbits/_mars/tensor/array_utils.py
python/xorbits/_mars/utils.py

1. pdated GitHub Actions CI/CD to install cudf-cu12==25.2.* instead of 24.10.*
Fixes #xxxx

ENH:  cuDF 25.2 compatibility
